apiVersion: v1
kind: LimitRange
metadata:
  name: pod-pvc-resources
  namespace: quota-demo
spec:
  limits:
    - type: Pod
      max:
        cpu: "1"
        memory: 512Mi
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi
