apiVersion: v1
kind: ResourceQuota
metadata:
  name: non-terminating-budget
  namespace: quota-demo
spec:
  scopes:
    - NotTerminating
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
