apiVersion: v1
kind: LimitRange
metadata:
  name: container-resources
  namespace: quota-demo
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 128Mi
      min:
        cpu: 50m
        memory: 32Mi
      max:
        cpu: 500m
        memory: 256Mi
      maxLimitRequestRatio:
        cpu: "2"
        memory: "2"
