apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-budget
  namespace: quota-demo
spec:
  hard:
    requests.cpu: 300m
    requests.memory: 256Mi
    limits.cpu: 800m
    limits.memory: 512Mi
    pods: "10"

