traefik:
  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    websecure:
      port: 8443
      exposedPort: 443
  gateway:
    listeners:
      # HTTPS listener for Gateway API
      websecure:
        port: 8443
        protocol: HTTPS
        namespacePolicy: All
        certificateRefs:
          - group: ""
            kind: Secret
            name: traefik-tls
            namespace: traefik

