apiVersion: v1
kind: Pod
metadata:
  name: echo
spec:
  restartPolicy: OnFailure
  containers:
    - name: echo
      image: busybox:1.28
      command: [ 'sh', '-c', 'echo "Hello, Kubernetes!" && sleep 5' ]
